/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.hello.ide;


/**
 * Use this class to register ide components.
 */
public class HelloLanguageIdeModule extends AbstractHelloLanguageIdeModule {
}
