/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.hello.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class HelloLanguageWebModule extends AbstractHelloLanguageWebModule {
}
