/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.hello.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.hello.HelloLanguageRuntimeModule;
import org.xtext.example.hello.HelloLanguageStandaloneSetup;
import org.xtext.example.hello.ide.HelloLanguageIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class HelloLanguageWebSetup extends HelloLanguageStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HelloLanguageRuntimeModule(), new HelloLanguageIdeModule(), new HelloLanguageWebModule()));
	}
	
}
