/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.hello.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link HelloLanguageWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractHelloLanguageWebModule extends DefaultWebModule {

}
