/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.hello.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHelloLanguageScopeProvider extends DelegatingScopeProvider {
}
